Hub/urls.py
from django.urls import path
from Hub import views

app_name = 'hub'

urlpatterns = [
    path('home/', views.home, name='home')
]

Match/urls.py
from django.urls import path
from Match import views

app_name = 'match'

urlpatterns = [
    path('all/', views.getAllMatches, name='get_all_matches'),
    path('create/match', views.createMatch, name='create_match'),
    path('update/<match_id>', views.updateMatch, name='update_match'),
    path('delete/<match_id>', views.deleteMatch, name='delete_match'),
    path('create/tournament', views.createTournament, name='create_tournament'),
    path('update/tournament/<tournament_id>',
         views.updateTournament, name='update_tournament'),
    path('delete/tournament/<tournament_id>',
         views.deleteTournament, name='delete_tournament'),
]

User/urls.py
from django.urls import path, include
from User import views

app_name = 'user'

urlpatterns = [
    path('login/', views.customLogin, name='login'),
    path('logout/', views.customLogout, name='logout'),
    path('register/', views.customRegister, name='register')
]

torneosApp/urls.py
from django.contrib import admin
from django.urls import path, include
from User import urls as userUrls
from Hub import urls as hubUrls
from Match import urls as matchUrls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(userUrls), name='user'),
    path('hub/', include(hubUrls), name='hub'),
    path('match/', include(matchUrls), name='match'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Hub/models.py
from django.db import models

# Create your models here.

Match/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now as timeNow


GAME_CHOICES = [
    ('FIFA', 'FIFA'),
    ('SMASH', 'Smash'),
]


class Match(models.Model):
    admin = models.ForeignKey(
        User, related_name='admin', default=1, on_delete=None)
    name = models.CharField(
        max_length=30, default='Match')
    game = models.CharField(
        max_length=10, choices=GAME_CHOICES, default='FIFA')
    date = models.DateField(default=timeNow)


class MatchEntry(models.Model):
    participant = models.ForeignKey(User, on_delete=None)
    match = models.ForeignKey(Match, on_delete=None)
    score = models.BigIntegerField(default=1)

User/models.py
from django.db import models
from django.contrib.auth.models import User


class User_extra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    profile_picture = models.FileField()

Match/forms.py
from django import forms
from .models import Match


class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['game']
        widgets = {
            'game': forms.TextInput(attrs={'class': 'validate'}),
        }

User/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import User_extra


class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'validate'}),
            'last_name': forms.TextInput(attrs={'class': 'validate'}),
            'username': forms.TextInput(attrs={'class': 'validate'}),
            'email': forms.TextInput(attrs={'class': 'validate'}),
        }


class UserExtraForm(forms.ModelForm):
    class Meta:
        model = User_extra
        fields = ['profile_picture']
        widgets = {
            'profile_picture': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        exclude = ('user', )

Hub/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User


def home(request):
    if request.user.is_authenticated:

        # get firstname or username as default
        if(request.user.first_name == ''):
            this_user = request.user.username
        else:
            this_user = request.user.first_name

        context = {
            'user': this_user,
        }

        return render(request, template_name='Hub/home.html', context=context)
    else:
        return redirect(reverse('user:login'))

Match/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User
from Match.models import Match

# Create your views here.


def getAllMatches(request):
    if request.user.is_authenticated:

        # get all matches
        matches = Match.objects.all()

        if(request.user.first_name == ''):
            this_user = request.user.username
        else:
            this_user = request.user.first_name

        context = {
            'user': this_user,
            'matches': matches,
        }

        return render(request, template_name='./Match/matches.html', context=context)
    else:
        redirect(reverse('user:login'))


def createMatch(request):
    pass


def updateMatch(request, match_id):
    pass


def deleteMatch(request, tournament_id):
    pass


def createTournament(request):
    pass


def updateTournament(request, tournament_id):
    pass


def deleteTournament(request, tournament_id):
    pass

User/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout, authenticate, login
from .forms import UserForm, UserExtraForm
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse


def customRegister(request):

    if(request.user.is_anonymous):
        this_user = 'Anonymous'
    else:
        this_user = request.user.first_name

    form = UserForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # form_extra = UserExtraForm(form.cleaned_data['filename'])
            # form_extra.user = user
            # form_extra.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('hub:home'))
        else:
            if len(form.cleaned_data['password']) < 8:
                form.add_error('password', 'La contraseña es muy corta')
            if 'username' in form.errors:
                form.add_error(
                    'username', 'Una cuenta ya ha sido registrada con ese usuario')
            if 'email' in form.errors:
                form.add_error('email', 'Ingresa un correo valido')

            context = {
                'user': this_user,
                'form': form,
                'errors': form.errors,
            }
            return render(request, template_name='User/register.html', context=context)
    else:
        context = {
            'user': this_user,
            'form': form,
            'errors': None,
        }

        return render(request, template_name='User/register.html', context=context)


def customLogin(request):
    if(request.user.is_anonymous):
        this_user = 'Anonymous'
    else:
        this_user = request.user.first_name

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return redirect(reverse('hub:home'))
        else:
            context = {
                'form': UserForm(None),
                'errors': True
            }
            return render(request, template_name='User/login.html', context=context)
    else:
        context = {
            'user': this_user,
            'form': UserForm(None),
            'error': False
        }
        return render(request, template_name='User/login.html', context=context)


def customLogout(request):
    logout(request)
    return redirect(reverse('user:login'))

Hub/templates/Hub/home.html
{% extends '../base.html' %} {% load static from staticfiles %}
<!-- -->
{% block Username %}{{user}}{% endblock %}
<div><p>holis</p></div>

Match/templates/Match/matches.html
{% extends 'base.html' %} {% block bodyContent %}

<div>
  {% for match in matches%} {{match.participants.all.0}} {% endfor %}
</div>
{% endblock %}

User/templates/User/login.html
{% extends 'base.html' %} {% block bodyContent %}

<div class="row container" style="margin-top: 50px">
  <form class="col s12" action="{% url 'user:login' %}" method="POST">
    {% csrf_token %}
    <!-- -->
    {% for formfield in form %}
    <!-- -->
    {% if formfield.name != 'email' and formfield.name != 'first_name' %}
    <!-- -->
    {% if formfield.name != 'last_name'%}
    <div class="row">
      <div class="input-field col s12">
        {{ formfield }}
        <label for="{{ formfield.id_of_label}}">{{ formfield.label }}</label>
      </div>
    </div>
    {% endif %}{% endif %} {% endfor %} {% if errors %}
    <div class="row">
      <div class="col s12">
        <span
          class="helper-text red lighten-3"
          data-error="wrong"
          data-success="right"
        >
          Username and/or password are invalid
        </span>
      </div>
    </div>
    {% endif %}
    <button
      class="btn waves-effect waves-light green"
      type="submit"
      name="action"
    >
      Login
      <i class="material-icons right">send</i>
    </button>
  </form>
  <div class="col s12" style="margin-top: 20px">
    <a href="{% url 'user:register' %}"> Go to register </a>
  </div>
</div>

{% endblock %}

User/templates/User/register.html
{% extends 'base.html' %} {% block bodyContent %}

<div class="row container" style="margin-top: 50px">
  <form class="col s12" action="{% url 'user:register' %}" method="POST">
    <div class="row">
      {% csrf_token %}
      <!-- -->
      {% for formfield in form%}
      <div class="row">
        <div class="input-field col s12">
          {{ formfield }}
          <label for="{{ formfields.id_of_label}}">{{ formfield.label }}</label>
        </div>
      </div>
      {%endfor %}
    </div>

    <button
      class="btn waves-effect waves-light green"
      type="submit"
      name="action"
    >
      Register
      <i class="material-icons right">send</i>
    </button>
  </form>
  <div class="col s12" style="margin-top: 20px">
    <a href="{% url 'user:login' %}"> Go to login </a>
  </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    {%block styleSheet%} {% endblock %}

    <link rel="stylesheet" href="{% static 'base.css' %}" />

    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <meta charset="UTF-8" />
    <title>JHub</title>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a
          href="#!"
          id="brand-logo-a"
          class="brand-logo"
          style="margin-left: 20px"
          >JHub</a
        >
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"
          ><i class="material-icons">menu</i></a
        >
        <ul
          id="content-nav-list"
          class="right hide-on-med-and-down"
          style="margin-right: 20px"
        >
          <li><a href="">Feed</a></li>
          <li><a href="">Matches</a></li>
          <li><a href="">Explore</a></li>
          <li>
            <a
              class="dropdown-trigger"
              href="#!"
              data-target="nav-user-dropdown"
            >
              {{user}}
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <ul id="nav-user-dropdown" class="dropdown-content">
      <li><a href="#!">Terms</a></li>
      <li><a href="#!">Settings</a></li>
      <li class="divider"></li>
      <li><a href="{% url 'user:logout' %}">Logout</a></li>
    </ul>

    <ul class="sidenav" id="mobile-demo">
      <li><a href="">Terms</a></li>
      <li><a href="">Settings</a></li>
      <li><a href="{% url 'user:logout' %}">Logout</a></li>
    </ul>

    <main>{% block bodyContent%} {% endblock %}</main>

    <footer class="page-footer" style="background:#006064;">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Acerca de JHub</h5>
            <p class="grey-text text-lighten-4">
              Un sitio para registrar partidas jugadas, acumular y canjear
              puntos y participar en torneos.
            </p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Redes</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
              <li>
                <a class="grey-text text-lighten-3" href="#!">Facebook</a>
              </li>
              <li>
                <a class="grey-text text-lighten-3" href="#!">Instagram</a>
              </li>
              <li><a class="grey-text text-lighten-3" href="#!">Youtube</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          © 2019 JHub
          <a class="grey-text text-lighten-4 right" href="#!"
            >Desarrollador de JHub</a
          >
        </div>
      </div>
    </footer>
  </body>

  <script src="{% static 'js/baseScript.js' %}"></script>
</html>